### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Swirren** [gecko10000/AdventureCalendar#1]
Please allow a config option to change the GUI background, my server uses black glass panes not gray.

It would also be great if the rewards could be sorted numerically, not all over the place

**Comment by Swirren** [comment]
Also it seems that the %adventurecalendar_timeuntil_next% placeholder returns the time until the 25th (last) gift, not day 1

**Comment by gecko10000** [comment]
> Also it seems that the %adventurecalendar_timeuntil_next% placeholder returns the time until the 25th (last) gift, not day 1

This may be because we're still in November, so it's using today (the 24th) as the current day.

**Comment by gecko10000** [comment]
Both of these have now been implemented as options.

**Comment by Swirren** [comment]
thank you very much!

**Comment by Swirren** [comment]
Hey there, I'm trying to add a command to acal but it's not parsing {player} properly, such as /eco give {player} 100

maybe I'm doing it wrong?

**Comment by Swirren** [comment]
nvm, saw in another part of the config that it's %player_name%
